### ISSUE TITLE
Motion control Y-axis flipped

### ISSUE THREAD

**Issue by MochaEcho321** [Roberto-Nessy/OoT3D_Standalone_Free_Cam#7]
Whenever I use the OoT3D Free-Cam mod the Y-axis of my motion controls is flipped for some reason, I'm thinking it may have something to due with my input settings but I can't seem to fix it. I use a Switch Pro Controller with SDL as my set motion control input if that helps.

**Comment by Roberto-Nessy** [comment]
Would you mind confirming a few things for me?
1. Do motion controls work normally without the mod
2. Are you on a normal or MQ file?
3. Have you inverted any axes?

Tbh I don't think 2 or 3 should affect it but they're worth considering
I can't replicate the issue on console and I haven't got citra motion controls set up so I can't test that

**Comment by SmoothCh1ken** [comment]
MAN. MAN I LOVE YOU SO MUCH! IT WORKS FLAWLESSLY. REALLY THANK YOU FOR THIS MOD. YOU'RE THE GOAT

**Comment by MochaEcho321** [comment]
Motion controls function normally without,
 Im not sure what an MQ file is
And I have not in verted any axies

**Comment by Roberto-Nessy** [comment]
Strange, the mod shouldn't affect anything when the free cam is disabled (as it should be anytime gyro controls are relevant) which is supported by it working on console.
MQ means master quest, I was wondering if I'd somehow mirrored both axes instead of just the horizontal one.

**Comment by MochaEcho321** [comment]
Just updated my mod, Citra, and configured my motion controls and It fixed itself 

Thank you so much for the help figuring this out and for making the mod I've needed since I first played the game
