### ISSUE TITLE
glitch in hyrule castle garden guard sequence

### ISSUE THREAD

**Issue by HueSandor** [Roberto-Nessy/OoT3D_Standalone_Free_Cam#9]
camera wont move at said location and is stuck to one point

**Comment by DragonKnightKX** [comment]
If you mean it won't move with the c-sitck, it's not supposed to.

**Comment by HueSandor** [comment]
No, what i meant was that the camera wont scroll with link. The auto camera thingy is stuck to the first scene

**Comment by RyanAshtari** [comment]
I'm having the same problem, gonna disable the patch until I've completed this portion of the game

**Comment by Roberto-Nessy** [comment]
This should now be fixed, not sure why exactly it occurred, but it seems to have been caused by attempting to enter free cam before the camera pans away from the crawlspace. Added a check to make sure you can't enter free cam in that scene at all.
